name: ZNear
version: 1.0.0
main: ZNear\Main
api: 5.0.0
commands:
  near:
    description: "Displays the number of players"
    usage: "/near"
    permission: "znear.command"
permissions:
  znear.command:
    description: "Permission to use /near"
    default: true
